#### Libraries needed ####

library(colorspace)
library(ggplot2)
library(jpeg)
library(gridExtra)
library(keras)
library(reticulate)

use_condaenv("base")
# Sys.setenv(RETICULATE_PYTHON="D:/Programi/Anaconda3/python.exe")
py_discover_config('keras')

# library(ggdendro)
# library(robustbase)
# library(dendextend)
# library(mvtnorm)
# library(animation)
# library(ape)
# library(FactoMineR)
# library(tree)
# library(randomForest)
# library(neuralnet)
# library(grid)
# library(imager)
# library(factoextra)

# install.packages("colorspace")
# install.packages("ggplot2")
# installed.packages("grid")
# install.packages("gridExtra")
# install.packages("factoextra")
# install.packages("ggdendro")
# install.packages("robustbase")
# install.packages("dendextend")
# install.packages("mvtnorm")
# install.packages("animation")
# install.packages("ape")
# install.packages("jpeg")
# install.packages("FactoMineR")
# install.packages("e1071") # for SVM
# install.packages("tree")
# install.packages("randomForest")
# install.packages("neuralnet")
# install.packages("imager")
# install.packages("keras")
# install_keras(conda = "D:/Programi/Anaconda3/Scripts/conda.exe", tensorflow = "gpu")